- hosts: web
  gather_facts: true
  tags: facts
  tasks:
    - name: Wait for SSH
      wait_for_connection:
        delay: 0
        timeout: 4000

- hosts: web
  tags: common
  gather_facts: true
  become: true
  module_defaults:
    apt:
      install_recommends: no
  roles:
    - role: common/network
    - role: common/utils
    - role: common/firewall
    - role: common/dns
    - role: common/sshd
    - role: common/users
    - role: common/fish
    - role: common/fail2ban
    - role: common/node
    - role: common/www

- hosts: cluster
  tags: cluster
  gather_facts: true
  become: true
  roles:
    - role: common/network
    - role: cluster/cni
    - role: cluster/docker/daemon
    - role: cluster/docker/skeleton

- import_playbook: ./sync-cluster.yml
